apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: challenge-cluster
type: Opaque
data:
  # PostgreSQL
  POSTGRES_USER: base64secret
  POSTGRES_PASSWORD: base64secret
  POSTGRES_DB: base64secret
  POSTGRES_PORT: base64secret
  POSTGRES_HOST: base64secret
  # RabbitMQ
  RABBITMQ_USER: base64secret
  RABBITMQ_PASSWORD: base64secret
  RABBITMQ_PORT: base64secret
  RABBITMQ_URI: base64secret
  # Redis
  REDIS_USER: base64secret
  REDIS_PASSWORD: base64secret
  REDIS_PORT: base64secret
  REDIS_HOST: base64secret
  REDIS_URI: base64secret

  # API Configuration
  API_PORT: base64secret
  ---
apiVersion: v1
kind: Secret
metadata:
  name: consumer-secrets
  namespace: challenge-cluster
type: Opaque
data:
  # PostgreSQL
  POSTGRES_USER: base64secret
  POSTGRES_PASSWORD: base64secret
  POSTGRES_DB: base64secret
  POSTGRES_PORT: base64secret
  POSTGRES_HOST: base64secret
  # RabbitMQ
  RABBITMQ_USER: base64secret
  RABBITMQ_PASSWORD: base64secret
  RABBITMQ_PORT: base64secret
  RABBITMQ_URI: base64secret